### ISSUE TITLE
Feature request: Add to Pop! Shop

### ISSUE THREAD

**Issue by lijamez** [cross-platform/apple-music-for-linux#10]
I'm running Pop! OS and I want to install this app without also installing the Snap store. Alternatively, also distribute the app as a Flatpak source (or on Flathub).

**Comment by lolrepeatlol** [comment]
I agree on this. Most distros have Flatpak support out of the box, not Snap support (and rightfully so, in my opinion.) Could you please publish this to Flathub?

**Comment by MarcusTomlinson** [comment]
I going to close this as I don’t have any plans to implement this in the near future myself. If someone would like to package this for another store, I’ll be happy to review.
