### ISSUE TITLE
Chromium icon? 

### ISSUE THREAD

**Issue by cherrz** [cross-platform/apple-music-for-linux#12]
How I can get rid of this Chromium icon when app is open? 
https://imgur.com/RH1lDgF

**Comment by MarcusTomlinson** [comment]
Hey @cherrz, what distro is this?

**Comment by cherrz** [comment]
> Hey @cherrz, what distro is this?

ElementaryOS.

**Comment by MarcusTomlinson** [comment]
Thanks, I’ll have a look tomorrow.

**Comment by cherrz** [comment]
> Thanks, I’ll have a look tomorrow.

Thanks a lot! Appreciate that.

**Comment by MarcusTomlinson** [comment]
Ok, I can reproduce the issue, but have no good ideas yet for a solution. I'll have to come back to this another time.

**Comment by MarcusTomlinson** [comment]
This is now fixed in version 0.5.
