### ISSUE TITLE
Apple Music fails to launch - cannot find chromium

### ISSUE THREAD

**Issue by Trapstre** [cross-platform/apple-music-for-linux#13]
**apple-music-for-linux** is unable to find chromium at the path in the launcher file. I cant change as it  is mounted on a read only file system. 
Error Below: 
**_./apple-music-for-linux.launcher: 33: exec: /usr/lib/chromium-browser/chromium-browser: not found_**

**Comment by MarcusTomlinson** [comment]
Are you trying to launch `/snap/apple-music-for-linux/current/apple-music-for-linux.launcher` directly?

You need to run the app one of the following ways:

`apple-music-for-linux`
`/snap/bin/apple-music-for-linux`
`snap run apple-music-for-linux`

Or find and launch the application from your distro's applications menu.
