### ISSUE TITLE
Unable to open Ubuntu 20.10 Wayland session GNOME 3.38

### ISSUE THREAD

**Issue by KevinParnell** [cross-platform/apple-music-for-linux#15]
Unable to open the regular release snap version as of sep 28 1:42pm eastern.

```
kevin@parnell:~$ snap run apple-music-for-linux
Unable to init server: Could not connect: Connection refused

(zenity:60415): Gtk-WARNING **: 13:43:54.390: cannot open display: :0
[60346:60346:0928/134355.388098:ERROR:browser_main_loop.cc(1469)] Unable to open X display.
kevin@parnell:~$
 ```

I will try it again in a X11 session and update.

**Comment by KevinParnell** [comment]
Works fine with X11. Ran into a similar issue with The Powder Toy as well, guess it's a display manager thing. Would be epic if wayland support could be added, really excited to try out this app though, has been basically the only program missing for me on Linux. Thanks king.

**Comment by KevinParnell** [comment]
The issue persists in a Wayland session when I try
```
kevin@parnell:~$ env DISABLE_WAYLAND=1 apple-music-for-linux
```
which makes sense since the same error pops up when you've already disabled wayland in the snap config.

**Comment by KevinParnell** [comment]
Also not a bug but something nice, as far as I can tell the beta works just fine on it too 
![image](https://user-images.githubusercontent.com/15918185/94469278-d4fb6e80-0193-11eb-865f-911046c3a109.png)

**Comment by MarcusTomlinson** [comment]
Thanks for the info, Kevin. I’ll look into this soon™ :)

**Comment by KevinParnell** [comment]
I appreciate it, looks like it's an issue with Zenity specifically, although I'm not entirely sure what's causing it to have an issue. Have a good one :)

**Comment by KevinParnell** [comment]
Alright did some more digging and it appears Chromium is to blame https://superuser.com/questions/1570106/can-anyone-make-chrome-and-or-chromium-post-version-78-work-over-ssh-x-forwardin

The issue is about ssh x forwarding but I imagine the x forwarding for wayland is similar in function. May just have to wait for a Chromium update or something it seems.

**Comment by MarcusTomlinson** [comment]
Looks like this is actually more widespread an issue: https://gitlab.gnome.org/GNOME/mutter/-/issues/1454

**Comment by MarcusTomlinson** [comment]
Hey all, could you please install the latest Apple Music snap via `snap refresh apple-music-for-linux` and let me know if this is now working.

Thanks!

**Comment by MarcusTomlinson** [comment]
@KevinParnell (& others affected), could you please try the latest version of the snap and see if this now works? Thanks!

**Comment by pythonInRelay** [comment]
Works fine on Wayland. You can close this.
