### ISSUE TITLE
/tmp/snap.rootfs_ permission issue

### ISSUE THREAD

**Issue by magni08** [cross-platform/apple-music-for-linux#18]
I have tried to install and it continues to fail at this folder due to permission issues. 

cannot perform the following tasks:
- Run configure hook of "apple-music-for-linux" snap if present (run hook "configure": cannot perform operation: mount --bind /var/lib/snapd/snap/core18/current/etc/apparmor /tmp/snap.rootfs_m2SE7t/etc/apparmor: Permission denied)

I have tried running as sudo and from the Snap store, yet each install creates a new rootfs_ folder, and each of the permissions are forbidden, so changing with chmod will not fix it.

**Comment by MarcusTomlinson** [comment]
Hi @magni08, what distro and version are you running?

**Comment by MarcusTomlinson** [comment]
Sounds like you're facing this: https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1729576
