### ISSUE TITLE
App doesn't work with a UK account - Needs configurable URL

### ISSUE THREAD

**Issue by nosami** [cross-platform/apple-music-for-linux#25]
It can be fixed by changing the URL to `https://music.apple.com/gb`. I changed the location using the developer console to the `gb` version of the URL and it worked fine after that.

**Comment by nosami** [comment]
Never mind, I see you do country code detection [here](https://github.com/cross-platform/apple-music-for-linux/blob/e4ef11f797e3b6cada018223448a64e6b7d2e8bf/dump/apple-music-for-linux.launcher#L30-L31`) and it worked fine on the 2nd launch.

**Comment by MarcusTomlinson** [comment]
For anyone interested, selecting a manual locale is now possible via `~/snap/apple-music-for-linux/common/locale` in version 0.7.0+ of the snap.

For example:

```
mkdir -p ~/snap/apple-music-for-linux/common
echo "DE" > ~/snap/apple-music-for-linux/common/locale
```

**Comment by mittler-works** [comment]
Thanks @MarcusTomlinson this works well!

**Comment by nbolton** [comment]
I opened a PR: https://github.com/cross-platform/apple-music-for-linux/pull/56
