### ISSUE TITLE
Ubuntu 21.04 on Raspberry Pi 4

### ISSUE THREAD

**Issue by JC1738** [cross-platform/apple-music-for-linux#26]
I installed the candidate snap and was able to launch the apple music player, sign in, and start playing songs.  There were a couple of errors, but things seemed to work ok.  The one issue I am seeing is all music shows the full length of time, however playback seems to be hard coded to 1:30.  It doesn't matter what song I choose it only plays for 1:30 and then goes on to the next song.

**Comment by MarcusTomlinson** [comment]
Hi, it's likely you're only being allowed to listen to non-DRM samples of tracks. The ARM build in candidate does not have DRM support. In fact, it essentially has no support at this time. It's still very much a WIP.

**Comment by MarcusTomlinson** [comment]
This issue is being tracked here https://github.com/cross-platform/apple-music-for-linux/issues/21
