### ISSUE TITLE
unable to set country

### ISSUE THREAD

**Issue by wjterveld** [cross-platform/apple-music-for-linux#27]
After installation on SuseLinux Tumbleweed iTunes asks to select my country, and suggests "Netherlands", witch is correct, but I'm unable to click on Choose??

**Comment by MarcusTomlinson** [comment]
Hi @wjterveld, you can override the auto locale detection via `~/snap/apple-music-for-linux/common/locale`.

For example:

```
echo "US" > ~/snap/apple-music-for-linux/common/locale
```
