### ISSUE TITLE
No supported source was found.

### ISSUE THREAD

**Issue by ck3mp3r** [cross-platform/apple-music-for-linux#29]
When trying to play a live apple music one station a popup appears "Failed to load because no supported source was found" accompanied by an in app error "An error occured. Playback error."

**Comment by MarcusTomlinson** [comment]
Hmm, live stations appear to be working for me at least. When this happens you could try pressing `Ctrl+R` to reload the page, and see if the issue goes away.

Otherwise you could try re-installing the snap by running:

```
snap remove apple-music-for-linux
rm -rf ~/snap/apple-music-for-linux
snap install apple-music-for-linux
```

And see if that solves your issue.

**Comment by ck3mp3r** [comment]
Been there, done that... also, keeps on forgetting the country I selected after logging in. Quitting out of the app and starting it agains solves that... not ideal though. Are there additional plugins required for this to work on a Raspberry Pi 4 running Ubuntu Hirsute?

**Comment by MarcusTomlinson** [comment]
You can force the locale selection via `~/snap/apple-music-for-linux/common/locale` If the auto detect keeps getting it wrong.

For example:

```
echo "GB" > ~/snap/apple-music-for-linux/common/locale
```

This snap isn’t yet supported on raspberry pi. See: https://github.com/cross-platform/apple-music-for-linux/issues/26

**Comment by ck3mp3r** [comment]
Closing re #26
