### ISSUE TITLE
Widevine failure on network with corporate ca-certificates

### ISSUE THREAD

**Issue by cmcquinn** [cross-platform/apple-music-for-linux#31]
![image](https://user-images.githubusercontent.com/7454432/128260880-a1fbbe62-4811-4336-af00-a8da32445664.png)
The snap fails to start on Ubuntu 20.04 on a corporate network due to not recognizing the ca-certificates.

**Comment by pythonInRelay** [comment]
Nothing that can be done about this, you need to use a network that doesn't inject it's own certificates.
