### ISSUE TITLE
Hi-Res settings not available

### ISSUE THREAD

**Issue by mhaigh53** [cross-platform/apple-music-for-linux#32]
I cannot believe how easy this was to install with snap on my ubuntu 20.4. I had the region problem but was fixed on a restart. I would like to stream some 24/96 music and cannot see where I can tell it to use any Hi_res modes.

Thanks again for such a great app.

**Comment by dogepotion** [comment]
It's just the web browser version of Apple Music in an Electron wrapper which means lossless is unfortunately not possible though this.
