### ISSUE TITLE
Can't use keyboard buttons to switch song or pause

### ISSUE THREAD

**Issue by jhartmann44** [cross-platform/apple-music-for-linux#35]
When I try to skip to the next song it won't do it, same thing with pausing.
When I use Apple Music in Chrome I can switch and pause songs.
I'm using Ubuntu 20.04 and the newest version of apple-music-for-linux

**Comment by MarcusTomlinson** [comment]
Duplicate of https://github.com/cross-platform/apple-music-for-linux/issues/8
