### ISSUE TITLE
"Item not available in your country" When trying to access radio stations

### ISSUE THREAD

**Issue by 003miles** [cross-platform/apple-music-for-linux#37]
I'm able to access the same stations from my apple devices and the store is set to the same country, but the following pop up still prevents me from accessing radio stations.
https://i.ibb.co/qCLK8yh/Screenshot-20211130-204639.png

**Comment by MarcusTomlinson** [comment]
Try this https://github.com/cross-platform/apple-music-for-linux/issues/24#issue-883818769

**Comment by tberta** [comment]
> Try this [#24 (comment)](https://github.com/cross-platform/apple-music-for-linux/issues/24#issue-883818769)

I had the same issue and it was indeed resolved by pressing Ctrl+R to reload the page 👍
