### ISSUE TITLE
Does not launch

### ISSUE THREAD

**Issue by Mase3206** [cross-platform/apple-music-for-linux#49]
The app installs just fine. It prompts you to install Widevine, installs that just fine, but when the app launches, it errors out. The error it gives me is "SIGTRAP". It also says it's trying to go to "music.apple.com_/us/browse"? Is that underscore supposed to be there?

**Comment by Mase3206** [comment]
This is what it shows me: 
![image](https://user-images.githubusercontent.com/35052448/211974448-6df9f1d6-278c-4f1e-9868-b6f847bad2d5.png)

**Comment by MarcusTomlinson** [comment]
I assume you’re trying to run the arm version of the snap? That build was experimental, I never actually got it working. Sorry.

**Comment by Mase3206** [comment]
Yeah, I’m running it on my Apple MacBook Air with the M1 processor. Do you know of a way to force the snap to use the x86 version? I know there’s a way to do it with apt. I have an emulator installed, though I can’t remember if it’s Box64 or something else—I had to try a bunch before one worked.
