### ISSUE TITLE
restart (Ubuntu or Apple Music) dont work:(

### ISSUE THREAD

**Issue by idanka** [cross-platform/apple-music-for-linux#5]
Thx, works!

> snap remove apple-music-for-linux
> rm -rf ~/snap/apple-music-for-linux
> snap install apple-music-for-linux --devmode

**Do not exchange Apple stores, and the application works!**
**but restart (Ubuntu or Apple Music) dont work:(**

_Originally posted by @idanka in https://github.com/cross-platform/apple-music-for-linux/issues/4#issuecomment-645252311_

**Comment by MarcusTomlinson** [comment]
Please could you try the following and let me know if this issue is resolved:

```
snap remove apple-music-for-linux
rm -rf ~/snap/apple-music-for-linux
snap install apple-music-for-linux --candidate --devmode
```

**Comment by idanka** [comment]
Uninstall/rm/install 
but For You not play music
[CONTENT_EQUIVALENT](https://www.idstudio.tk/media/2020-06-23_06-34-45.png)

**Comment by Ultraphaze** [comment]
Hello Idanka,

CONTENT_EQUIVALENT pops up on my Macbook only the first time I start Apple Music. I let the App save my password, restarted the application and now everything works without problems.

@MarcusTomlinson why I have to load on every start Widevine?

"This application requires Widevine™ in order to play DRM protected media.

Would you like to download it now?

(For more info visit: https://www.widevine.com)"

Is there no way to save the plugin?

Manjaro - 5.7.0-3
MacbookAir (11, early 2014)

**Comment by MarcusTomlinson** [comment]
@Ultraphaze, please open a terminal and launch Apple Music (by typing `apple-music-for-Linux`), run through the process of downloading Widevine until the actual app opens, then share the terminal output here. Thanks.

**Comment by Ultraphaze** [comment]
Hello Marcus,

thank you for the quick response. here we go:

[adrian@MBA ~]$ /var/lib/snapd/snap/bin/apple-music-for-linux
Gtk-Message: 08:51:07.561: GtkDialog mapped without a transient parent. This is discouraged.
libGL error: MESA-LOADER: failed to retrieve device information
libGL error: Version 4 or later of flush extension not found
libGL error: failed to load driver: i915
libGL error: MESA-LOADER: failed to retrieve device information
MESA-LOADER: failed to retrieve device information
[6718:6718:0625/085110.689803:ERROR:context_group.cc(410)] ContextResult::kFatalFailure: too few texture image units supported (0, should be 8).
[6718:6718:0625/085110.827797:ERROR:context_group.cc(410)] ContextResult::kFatalFailure: too few texture image units supported (0, should be 8).
[6641:6726:0625/085114.169215:ERROR:udev_watcher.cc(96)] Failed to begin udev enumeration.
[adrian@MBA ~]$

**Comment by MarcusTomlinson** [comment]
Can you tell me if this file exists on your system: `~/snap/apple-music-for-linux/current/.local/lib/WidevineCdm/_platform_specific/linux_x64/libwidevinecdm.so`

**Comment by Ultraphaze** [comment]
There is no .local in /var/lib/snapd/snap/apple-music-for-linux/current/

[adrian@MBA current]$ cd /var/lib/snapd/snap/apple-music-for-linux/current/
[adrian@MBA current]$ ls -a -l
insgesamt 6
drwxr-xr-x 10 root root  171 22. Jun 23:30 .
drwxr-xr-x  3 root root 4096 24. Jun 21:25 ..
-rwxrwxr-x  1 root root 1616 22. Jun 23:24 apple-music-for-linux.launcher
drwxr-xr-x  5 root root   56 22. Jun 23:30 data-dir
drwxr-xr-x 13 root root  202 22. Jun 23:29 etc
drwxr-xr-x  2 root root    3 22. Jun 23:28 gnome-platform
drwxr-xr-x  3 root root   64 22. Jun 23:30 lib
drwxr-xr-x  3 root root   43 22. Jun 23:30 meta
drwxr-xr-x  3 root root   36 22. Jun 23:30 snap
drwxr-xr-x  7 root root  101 22. Jun 23:28 usr
drwxr-xr-x  4 root root   39 22. Jun 23:28 var
[adrian@MBA current]$

**Comment by MarcusTomlinson** [comment]
I meant `$HOME/snap/apple-music-for-linux/current/.local/lib/WidevineCdm/_platform_specific/linux_x64/libwidevinecdm.so`

It'd surprise me if the the app actually worked (i.e. you can log in and play DRM music) without that file present. I am a little concerned about the way you're executing the app actually (`/var/lib/snapd/snap/bin/apple-music-for-linux`). Could you run it either by `apple-music-for-linux` or `snap run apple-music-for-linux`.

Alternatively, if everything is working for you the way you're running it, you could just do the following to stop those Widevine prompts:

```
mkdir -p $HOME/snap/apple-music-for-linux/current/.local/lib/WidevineCdm/_platform_specific/linux_x64
touch $HOME/snap/apple-music-for-linux/current/.local/lib/WidevineCdm/_platform_specific/linux_x64/libwidevinecdm.so
```

**Comment by MarcusTomlinson** [comment]
@idanka, I've just seen this CONTENT_EQUIVALENT error for the first time myself.

Workaround: Press `Ctrl+R` to reload the page, and the issue will go away.
