### ISSUE TITLE
Error: Item not available in your country

### ISSUE THREAD

**Issue by nbolton** [cross-platform/apple-music-for-linux#55]
Whenever you try to play any song...

![image](https://github.com/cross-platform/apple-music-for-linux/assets/313427/68fdef09-d994-4bb3-9dce-4cbba6f67f13)

To fix:
1. Scroll to the bottom of any page
2. Click 'United States'
3. Choose the correct country

Suggestion: Tell the user they need to do this when the app first starts.

**Comment by MarcusTomlinson** [comment]
Hi, you can set your locale like this: https://github.com/cross-platform/apple-music-for-linux/issues/25#issuecomment-851724255

**Comment by nbolton** [comment]
https://github.com/cross-platform/apple-music-for-linux/pull/56
