### ISSUE TITLE
Unable to Login to Apple Music for Linux under Ubuntu 22.04.3 LTS

### ISSUE THREAD

**Issue by Nikkor10528git** [cross-platform/apple-music-for-linux#57]
I have been using Apple Music for Linux with no problems for several months and logged into my Apple ID.  Starting a few days ago, the app asked me to sign in.  When I enter my credentials, the app clears the model and returns to the main screen with the sign-in button.

Do you have any suggestions?

Paul.

**Comment by Nikkor10528git** [comment]
I resolved the issue by doing a snap remove followed by a snap install.   Login is working now.  A Ubuntu or app update broke Apple Music.

**Comment by imp667** [comment]
> I resolved the issue by doing a snap remove followed by a snap install. Login is working now. A Ubuntu or app update broke Apple Music.

Thanks for this! This was the solution for me too. Thanks again :-) 

sudo snap remove apple-music-for-linux then sudo snap install apple-music-for-linux
