### ISSUE TITLE
Attempting to play any music shows a large popup with ¨CONTENT_EQUIVALENT¨ and no music plays

### ISSUE THREAD

**Issue by 23Aaron** [cross-platform/apple-music-for-linux#9]
Linux Version: Pop_OS! 20.04 LTS

**Comment by 23Aaron** [comment]
Fixed by downloading chromium and allowing popups from music.apple.com

**Comment by MarcusTomlinson** [comment]
Duplicate of: https://github.com/cross-platform/apple-music-for-linux/issues/6
